config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      post :import
    end
  end

  devise_for :users

  # forum_posts are always accessed with their parent forum thread.
  resources :forum_threads do
    resources :forum_posts, module: :forum_thread
  end

  resources :notifications do
    member do
      post :mark_as_read
    end
  end

  root "forum_threads#index"
end

app/models/forum_thread.rb
# == Schema Information
#
# Table name: forum_threads
#
#  id         :integer          not null, primary key
#  user_id    :integer
#  title      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class ForumThread < ApplicationRecord
  belongs_to :user

  # http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#module-ActiveRecord::NestedAttributes::ClassMethods-label-Validating+the+presence+of+a+parent+model
  has_many :forum_posts, inverse_of: :forum_thread
  has_many :users, through: :forum_posts

  accepts_nested_attributes_for :forum_posts

  validates :title, presence: true
end

app/controllers/forum_thread/forum_posts_controller.rb
class ForumThread::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new(forum_post_params)
    @forum_post.user = current_user
    if @forum_post.save

      # Send the notifications to the rest of the users in this thread.
      recipients = (@forum_thread.users.uniq - [current_user])
      recipients.each do |recipient|
        Notification.posted(recipient: recipient, actor: current_user, notifiable: @forum_post)
      end

      flash[:notice] = "Successfully posted"
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}")
    else
      render "forum_threads/show"
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/forum_threads_controller.rb
class ForumThreadsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_forum_thread, only: [:show, :edit, :update, :destroy]

  def index
    @forum_threads = ForumThread.all
  end

  def show
    @forum_post = ForumPost.new
  end

  def new
    @forum_thread = ForumThread.new

    # A forum_post instance in memory for nesting it in the form.
    @forum_thread.forum_posts.new
  end

  def create
    # Set user_id on the new forum_thread and forum_post.
    # NOTE: Because these must be associated with current_user, it is a good idea
    # to hard-code the logic here rather than do it in the HTML form.
    @forum_thread = current_user.forum_threads.new(forum_thread_params)
    @forum_thread.forum_posts.first.user_id = current_user.id

    if @forum_thread.save
      redirect_to @forum_thread
    else
      render action: :new
    end
  end

  def edit
  end

  def update
    if @forum_thread.update(forum_thread_params)
      redirect_to @forum_thread
    else
      render action: :edit
    end
  end

  def destroy
    @forum_thread.destroy
    redirect_to forum_threads_path
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:id])
    end

    def forum_thread_params
      params.require(:forum_thread).permit(:title, forum_posts_attributes: [:id, :body])
    end
end

app/views/forum_threads/edit.html.slim
h1 Edit Forum Thread

= render "form"

app/views/forum_threads/index.html.slim
= link_to "New Thread", new_forum_thread_path, class: "btn btn-primary pull-right" 

h1 Threads

ul
  - @forum_threads.each do |forum_thread| 
    li = link_to forum_thread.title, forum_thread 

app/views/forum_threads/new.html.slim
h1 New Forum Thread

= form_for @forum_thread do |f| 
  .form-group
    = f.label :title 
    = f.text_field :title, class: "form-control" 

    = f.fields_for :forum_posts do |f_post|
      .form-group
        = f_post.label :body 
        = f_post.text_area :body, placeholder: "Add a comment", rows: 10, class: "form-control" 
  
  .form-group
    = f.submit class: "btn btn-primary" 

app/views/forum_threads/show.html.slim
p = link_to "Back to all threads", forum_threads_path

h1 = @forum_thread.title 

- @forum_thread.forum_posts.includes(:user).each do |forum_post| 
  = render 'forum_threads/forum_posts/forum_post', forum_post: forum_post

hr
= render partial: "forum_threads/forum_posts/form" 