config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      post :import
    end
  end

  devise_for :users

  # forum_posts are always accessed with their parent forum thread.
  resources :forum_threads do
    resources :forum_posts, module: :forum_thread
  end

  resources :notifications do
    member do
      post :mark_as_read
    end
  end

  root "forum_threads#index"
end

app/models/forum_post.rb
# == Schema Information
#
# Table name: forum_posts
#
#  id              :integer          not null, primary key
#  forum_thread_id :integer
#  user_id         :integer
#  body            :text
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class ForumPost < ApplicationRecord
  belongs_to :forum_thread
  belongs_to :user

  validates :forum_thread, presence: true
end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id              :integer          not null, primary key
#  recipient_id    :integer
#  actor_id        :integer
#  read_at         :datetime
#  action          :string
#  notifiable_id   :integer
#  notifiable_type :string
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class Notification < ApplicationRecord

  belongs_to :actor,     class_name: "User"  # A user who has triggered a notification.
  belongs_to :recipient, class_name: "User"  # A user who will receive that notification.

  belongs_to :notifiable, polymorphic: true  # Notifiable can be anything.

  scope :unread, ->{ where(read_at: nil) }
  scope :recent, ->{ order(created_at: :desc).limit(5) }

  def self.posted(actor:, recipient:, notifiable:)
    Notification.create!(action: "posted", recipient: recipient, actor: actor, notifiable: notifiable)
  end

  def self.follow(actor:, recipient:, notifiable:)
    Notification.create!(action: "follow", recipient: recipient, actor: actor, notifiable: notifiable)
  end

  def unread?
    !read_at
  end
end

app/controllers/forum_thread/forum_posts_controller.rb
class ForumThread::ForumPostsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_forum_thread

  def create
    @forum_post = @forum_thread.forum_posts.new(forum_post_params)
    @forum_post.user = current_user
    if @forum_post.save

      # Send the notifications to the rest of the users in this thread.
      recipients = (@forum_thread.users.uniq - [current_user])
      recipients.each do |recipient|
        Notification.posted(recipient: recipient, actor: current_user, notifiable: @forum_post)
      end

      flash[:notice] = "Successfully posted"
      redirect_to forum_thread_path(@forum_thread, anchor: "forum_post_#{@forum_post.id}")
    else
      render "forum_threads/show"
    end
  end

  private

    def set_forum_thread
      @forum_thread = ForumThread.find(params[:forum_thread_id])
    end

    def forum_post_params
      params.require(:forum_post).permit(:body)
    end
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :authenticate_user!

  # GET    /notifications.json
  def index
    # Get recent notifications addresed to current_user, whether read or not.
    @notifications = Notification.where(recipient: current_user).recent
  end

  # POST   /notifications/1/mark_as_read.json
  def mark_as_read
    notification = Notification.find(params[:id])

    unless notification.unread?
      render(nothing: true) and return
    end

    # Mark as read the specified notification.
    notification.update!(read_at: Time.zone.now)

    # Send the updated JSON list of notification back to the browser.
    @notifications = Notification.where(recipient: current_user).recent

    respond_to do |format|
      format.js { }
    end
  end
end

app/helpers/forum_posts_helper.rb
module ForumPostsHelper
  # https://github.com/jch/html-pipeline
  # gem 'html-pipeline'
  # gem 'github-markdown'
  # gem 'sanitize'
  def markdownify(content)
    pipeline_context = { gfm: true}
    pipeline_filters = [
      HTML::Pipeline::MarkdownFilter,     # Transform Markdown source into Markdown HTML.
      HTML::Pipeline::SanitizationFilter, # Filter out script tags. Always use it.
    ]
    pipeline = HTML::Pipeline.new(pipeline_filters, pipeline_context)
    pipeline.call(content)[:output].to_s.html_safe
  end
end

app/views/notifications/forum_posts/_posted.html.slim
-# A notification dropdown item for recently-posted thread posts.
-# Required locals: notification

-# Marks as read the clicked notification item by sending an async request to the server.
-# Jump to the actual content of the clicked notification item by using Turbolinks.visit function.

- dom_class = "dropdown-item notification_item #{"unread" if !notification.read_at?}"
- dom_id    = dom_id(notification.notifiable)

= link_to mark_as_read_notification_path(notification.id), class: dom_class, id:dom_id, method: :post, remote: true do
  | #{notification.actor.email} #{notification.action} #{notification.notifiable_type.underscore.humanize.downcase}

- jump_to_notifiable = forum_thread_path(notification.notifiable.forum_thread, anchor: dom_id)

javascript:
  // Jump to the clicked notification item.
  document.querySelector("##{dom_id}").addEventListener('click', (e) => {
    e.preventDefault()
    document.querySelector('#unredCountDropdown').click() // Close the dropdown.
    Turbolinks.visit("#{jump_to_notifiable}")             // Jump to the notifiable.
  })